apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.junovfx.com
spec:
  group: junovfx.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                uid:
                  type: integer
  scope: Namespaced
  names:
    plural: users
    singular: user
    kind: User
    shortNames:
    - u
