namespace:                          # Namespace to deploy the Titan server to

titan:
  image:                            # Registry to pull the Titan server image from

  owner:                            # Owner of the cluster

  node_selector:                    # Node selector to deploy the Titan server to
    enable: true                    # Enable node selector
    labels:                         # Node selector to deploy the Titan server to
      kubernetes.io/arch: amd64

  autoscaling:
    min_replicas: 3                 # Minimum number of replicas to run
    max_replicas: 5                 # Maximum number of replicas to run
