apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: titan
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: titan
subjects:
  - kind: ServiceAccount
    name: titan
