apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mars
  namespace: {{ .Values.mars.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mars
  minReplicas: {{ .Values.mars.autoscaling.min_replicas }}
  maxReplicas: {{ .Values.mars.autoscaling.min_replicas }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 30
  metrics:
    - type: ContainerResource
      containerResource:
        name: cpu
        container: mars
        target:
          type: Utilization
          averageUtilization: 50
